name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    Ubuntu:
        runs-on: ubuntu-latest    
        steps: 
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Build"
              run: make
            - name: "Upload"
              uses: actions/upload-artifact@v1
              with:
                name: "extractor-ubuntu-${{ github.sha }}.zip"
                path: |
                  ../extractor 
                  ../jpextractor
                  ../hiragana.txt
                  ../katakana.txt
                  ../kanji.txt
    Windows:
        runs-on: windows-latest    
        steps: 
            - name: "Checkout"
              uses: actions/checkout@v2
            - name: "Build"
              run: make
            - name: "Upload"
              uses: actions/upload-artifact@v2
              with:
                name: "extractor-win-${{ github.sha }}.zip"
                path: |
                  ../extractor.exe
                  ../jpextractor.exe
                  ../hiragana.txt
                  ../katakana.txt
                  ../kanji.txt
